blank_issues_enabled: true
contact_links:
  - name: Telegram
    url: https://t.me/bestdeejay
    about: Direct contact with Sergey
  - name: Email
    url: mailto:bestdeejay@ya.ru
    about: Professional inquiries
